"""add question model

Revision ID: 88ab38703c3c
Revises: 5b9968e96844
Create Date: 2025-08-07 18:01:51.750854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ab38703c3c'
down_revision: Union[str, Sequence[str], None] = '5b9968e96844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
    

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('id_subcategory', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_subcategory'], ['subcategories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
